import { useState } from 'react';
import { X, CheckCircle, AlertTriangle, Shield, ArrowUpRight } from 'lucide-react';
import { Alert, ResolutionType } from '../types';

interface ResolutionModalProps {
  alert: Alert;
  onClose: () => void;
  onResolve: () => void;
}

export function ResolutionModal({ alert, onClose, onResolve }: ResolutionModalProps) {
  const [resolutionType, setResolutionType] = useState<ResolutionType>('remediated');
  const [falsePositiveReason, setFalsePositiveReason] = useState('');
  const [notes, setNotes] = useState('');

  const getAutoGeneratedSummary = () => {
    switch (resolutionType) {
      case 'remediated':
        return `Alert "${alert.title}" has been remediated. Resource "${alert.resource}" security issues have been addressed. Business impact: ${alert.businessUnit} operations secured. Compliance frameworks affected: ${alert.complianceFrameworks.join(', ') || 'None'}.`;
      case 'false-positive':
        return `Alert "${alert.title}" marked as false positive. Resource "${alert.resource}" does not pose actual security risk. Reason: ${falsePositiveReason || 'Not specified'}.`;
      case 'accepted-risk':
        return `Alert "${alert.title}" accepted as known risk. Resource "${alert.resource}" risk acknowledged by ${alert.owner}. Business justification documented.`;
      case 'escalated':
        return `Alert "${alert.title}" escalated to senior security team. Resource "${alert.resource}" requires additional investigation. Business unit ${alert.businessUnit} notified.`;
    }
  };

  const handleResolve = () => {
    // In a real app, this would save to backend
    console.log('Resolving alert:', {
      alertId: alert.id,
      resolutionType,
      falsePositiveReason,
      notes,
      summary: getAutoGeneratedSummary()
    });
    onResolve();
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-start justify-between p-6 border-b border-gray-200">
          <div>
            <h2 className="text-xl mb-1">Resolve Alert</h2>
            <p className="text-sm text-gray-600">{alert.title}</p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          {/* Resolution Type */}
          <div>
            <label className="block text-sm mb-3">Resolution Type</label>
            <div className="grid grid-cols-2 gap-3">
              <button
                onClick={() => setResolutionType('remediated')}
                className={`p-4 rounded-lg border-2 transition-all ${
                  resolutionType === 'remediated'
                    ? 'border-green-500 bg-green-50'
                    : 'border-gray-200 hover:border-gray-300'
                }`}
              >
                <CheckCircle className={`w-5 h-5 mb-2 ${
                  resolutionType === 'remediated' ? 'text-green-600' : 'text-gray-400'
                }`} />
                <p className="text-sm">Remediated</p>
              </button>
              <button
                onClick={() => setResolutionType('false-positive')}
                className={`p-4 rounded-lg border-2 transition-all ${
                  resolutionType === 'false-positive'
                    ? 'border-blue-500 bg-blue-50'
                    : 'border-gray-200 hover:border-gray-300'
                }`}
              >
                <AlertTriangle className={`w-5 h-5 mb-2 ${
                  resolutionType === 'false-positive' ? 'text-blue-600' : 'text-gray-400'
                }`} />
                <p className="text-sm">False Positive</p>
              </button>
              <button
                onClick={() => setResolutionType('accepted-risk')}
                className={`p-4 rounded-lg border-2 transition-all ${
                  resolutionType === 'accepted-risk'
                    ? 'border-yellow-500 bg-yellow-50'
                    : 'border-gray-200 hover:border-gray-300'
                }`}
              >
                <Shield className={`w-5 h-5 mb-2 ${
                  resolutionType === 'accepted-risk' ? 'text-yellow-600' : 'text-gray-400'
                }`} />
                <p className="text-sm">Accepted Risk</p>
              </button>
              <button
                onClick={() => setResolutionType('escalated')}
                className={`p-4 rounded-lg border-2 transition-all ${
                  resolutionType === 'escalated'
                    ? 'border-orange-500 bg-orange-50'
                    : 'border-gray-200 hover:border-gray-300'
                }`}
              >
                <ArrowUpRight className={`w-5 h-5 mb-2 ${
                  resolutionType === 'escalated' ? 'text-orange-600' : 'text-gray-400'
                }`} />
                <p className="text-sm">Escalate</p>
              </button>
            </div>
          </div>

          {/* Conditional: False Positive Reason */}
          {resolutionType === 'false-positive' && (
            <div>
              <label className="block text-sm mb-2">Reason for False Positive</label>
              <select
                value={falsePositiveReason}
                onChange={(e) => setFalsePositiveReason(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">Select a reason...</option>
                <option value="expected-behavior">Expected Behavior</option>
                <option value="test-activity">Test Activity</option>
                <option value="missing-dependency">Missing Context/Dependency</option>
                <option value="incorrect-detection">Incorrect Detection Logic</option>
              </select>
              <p className="text-xs text-gray-600 mt-2">
                This feedback helps improve alert accuracy and reduce noise over time.
              </p>
            </div>
          )}

          {/* Auto-Generated Summary */}
          <div>
            <label className="block text-sm mb-2">Auto-Generated Summary</label>
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
              <p className="text-sm text-gray-700 leading-relaxed">
                {getAutoGeneratedSummary()}
              </p>
            </div>
            <p className="text-xs text-gray-600 mt-2">
              This summary is automatically generated from your investigation timeline and actions, 
              creating a compliance-ready audit trail.
            </p>
          </div>

          {/* Additional Notes */}
          <div>
            <label className="block text-sm mb-2">Additional Notes (Optional)</label>
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Add any additional context or observations..."
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
              rows={4}
            />
          </div>

          {/* Annotation */}
          <div className="bg-purple-50 border border-purple-200 rounded-lg p-4">
            <div className="flex items-start gap-3">
              <div className="w-6 h-6 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center flex-shrink-0 text-xs">
                6
              </div>
              <div>
                <p className="text-xs text-purple-900 mb-1">
                  <strong>The Feedback Loop:</strong> We don't just close the alert; we learn from it.
                </p>
                <p className="text-xs text-purple-700">
                  By capturing the reason for "False Positive," we capture tribal knowledge. 
                  This data feeds back into the Risk Score engine to suppress similar noise in the future.
                </p>
              </div>
            </div>
          </div>

          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <div className="flex items-start gap-3">
              <div className="w-6 h-6 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center flex-shrink-0 text-xs">
                7
              </div>
              <div>
                <p className="text-xs text-blue-900 mb-1">
                  <strong>Auto-Generated Audit Log:</strong> Save 5-10 minutes of paperwork.
                </p>
                <p className="text-xs text-blue-700">
                  The summary is auto-generated from the investigation timeline and your actions, 
                  creating a compliance-ready audit trail instantly.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-3 p-6 border-t border-gray-200 bg-gray-50">
          <button
            onClick={onClose}
            className="px-4 py-2 text-gray-700 hover:text-gray-900"
          >
            Cancel
          </button>
          <button
            onClick={handleResolve}
            className="px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
          >
            Resolve & Close Alert
          </button>
        </div>
      </div>
    </div>
  );
}
